### PR TITLE
lint: unify formatting Black with Ruff

### PR DESCRIPTION
**Pull request by Borda**
As Ruff is already used in this project and it is fully [compatible with Black formatting](https://astral.sh/blog/the-ruff-formatter), I would suggest using Ruff for all to reduce eventual collision between linting and formatting

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Thanks!! I will review these next week. I try to keep several different repos linting/ci stuff in sync so I can automate these kinds of linting  / CI changes at the same time. So I will update the other repos at the same time.

**Comment by Borda** [comment]
@jarrodmillman, did you have a chance to have a look at this PR? :flamingo:

**Comment by Borda** [comment]
@jarrodmillman friendly ping if you could have a look... :chipmunk:

**Comment by Borda** [comment]
it seems it was merged in @jarrodmillman's PR #123

**Pull request closed without merging**
